### ISSUE TITLE
1.0.20 Causes Crash with MooFluid Cows

### ISSUE THREAD

**Issue by Kumomo** [Sunekaer/stoneBlock#322]
## Bug Report
After updating to 1.0.20 from 1.0.17, initial load of each person's base with the presence of moofluid cows causes the server to crash. After the first crash from loading these areas it seems to run fine, though it seems like a number of fluid cows were removed.

After looking into it a bit more, most of the molten cows that I'd placed in soul vials before can no longer be released (iron, copper, etc) or cause server to crash and do not seem to spawn when using the Spawn Fluid Cow egg creatively.

I've also crashed once more after loading areas with fluid cows once, that had the same crash log as before.

Were all these fluid cows meant to be removed? I don't think I saw anything related to it in the changelogs.

Edit: 1.0.18 does not crash due to moofluid cows, can place vialed moo fluid cows normally, no cows deleted, no errors. 
Edit2: 1.0.19 does not crash immediately but it deleted the single moofluid cow I had in my base, pops up the same debug log errors but does not crash when placing certain vialed moo fluid cows in the world, crashes when porting to other bases that have moo fluid cows. (same crash log errors included in second crash log link below)

## Steps to Reproduce (for bugs)
Update to 1.0.20
Login or teleport to a base with moofluid cows (Not sure which cows specifically cause it as some cows were deleted and some were not; a lot of them seem to no longer be spawnable too).
Server crashes
Log back in and server is fine until you move to another area with moofluid cows (bases without them do not cause the crash).

## Logs
* Client/Server Log: Debug log shows a lot of these https://pastebin.com/H69sQm3e
* Crash Log: 1.0.20: https://pastebin.com/mgdjVtB7  1.0.19: https://pastebin.com/TrgQby5H

## Client Information
* Modpack Version: 1.0.20
* Server/LAN/Single Player: Server
* Optifine Installed: No
* Shaders Enabled: No

**Comment by Nazta** [comment]
It seems the buildcraft cows where removed.

I'm guessing it messed with entity IDs and now hard crash the server if any moofluid eneity is present.

**Comment by xILikepuddingx** [comment]
we did the same. wie update from 1.0.16 to 1.0.20. We saw MooFluid crashes the because many fluids are removed(?). but we fixed this on our servers. removed fluid cows are now water cows

**Comment by Kumomo** [comment]
You fixed it by making the other fluids water you mean?
How did you do this? Do you know if it's possible to retain the other fluids?

It's a private server I'm running for a few friends and half of them have been using some of the fluid cows as material sources for ingots, so if possible I'd like to keep the fluid cows.

**Comment by Y0ungSandwich** [comment]
Still present in 1.0.21
https://gist.github.com/Y0ungSandwich/41152f84c6e07c4f30dc01c4cfa08960

**Comment by xILikepuddingx** [comment]
our coder changed the file a bit @Sunekaer

**Comment by Sunekaer** [comment]
removed Moo FLuids in 1.0.24
